### ISSUE TITLE
change querying result to `JSON` instead of `MAP`.

### ISSUE THREAD

**Issue by ibilux** [surrealdb/surrealdb.wasm#16]
The current querying result return a `MAP` objects.
It's better to return the results in `JSON` format.

**Comment by ibilux** [comment]
This PR #28 should solve this issue.

**Comment by christophermiles** [comment]
I have the 0.6.0 release but I am still getting maps back from the queries, not objects
